/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InlineResponse2004,
    InlineResponse2004FromJSON,
    InlineResponse2004ToJSON,
} from '../models';

/**
 * StatusApi - interface
 * 
 * @export
 * @interface StatusApiInterface
 */
export interface StatusApiInterface {
    /**
     * 詳細内容
     * @summary 未ログインユーザーも含めたユーザーの状態を取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatusApiInterface
     */
    statusGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<InlineResponse2004>>;

    /**
     * 詳細内容
     * 未ログインユーザーも含めたユーザーの状態を取得
     */
    statusGet(initOverrides?: RequestInit): Promise<InlineResponse2004>;

}

/**
 * 
 */
export class StatusApi extends runtime.BaseAPI implements StatusApiInterface {

    /**
     * 詳細内容
     * 未ログインユーザーも含めたユーザーの状態を取得
     */
    async statusGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<InlineResponse2004>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2004FromJSON(jsonValue));
    }

    /**
     * 詳細内容
     * 未ログインユーザーも含めたユーザーの状態を取得
     */
    async statusGet(initOverrides?: RequestInit): Promise<InlineResponse2004> {
        const response = await this.statusGetRaw(initOverrides);
        return await response.value();
    }

}
