<?php
/**
 * ComparisonsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  App\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Tutorial
 *
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\OpenAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use App\OpenAPI\ApiException;
use App\OpenAPI\Configuration;
use App\OpenAPI\HeaderSelector;
use App\OpenAPI\ObjectSerializer;

/**
 * ComparisonsApi Class Doc Comment
 *
 * @category Class
 * @package  App\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ComparisonsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'comparisonsComparisonIdDelete' => [
            'application/json',
        ],
        'comparisonsComparisonIdGet' => [
            'application/json',
        ],
        'comparisonsComparisonIdPublishPost' => [
            'application/json',
        ],
        'comparisonsPost' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation comparisonsComparisonIdDelete
     *
     * 比較情報を削除
     *
     * @param  int $comparisonId comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdDelete'] to see the possible values for this operation
     *
     * @throws \App\OpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function comparisonsComparisonIdDelete($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdDelete'][0])
    {
        $this->comparisonsComparisonIdDeleteWithHttpInfo($comparisonId, $contentType);
    }

    /**
     * Operation comparisonsComparisonIdDeleteWithHttpInfo
     *
     * 比較情報を削除
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdDelete'] to see the possible values for this operation
     *
     * @throws \App\OpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function comparisonsComparisonIdDeleteWithHttpInfo($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdDelete'][0])
    {
        $request = $this->comparisonsComparisonIdDeleteRequest($comparisonId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation comparisonsComparisonIdDeleteAsync
     *
     * 比較情報を削除
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function comparisonsComparisonIdDeleteAsync($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdDelete'][0])
    {
        return $this->comparisonsComparisonIdDeleteAsyncWithHttpInfo($comparisonId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation comparisonsComparisonIdDeleteAsyncWithHttpInfo
     *
     * 比較情報を削除
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function comparisonsComparisonIdDeleteAsyncWithHttpInfo($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdDelete'][0])
    {
        $returnType = '';
        $request = $this->comparisonsComparisonIdDeleteRequest($comparisonId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'comparisonsComparisonIdDelete'
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function comparisonsComparisonIdDeleteRequest($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdDelete'][0])
    {

        // verify the required parameter 'comparisonId' is set
        if ($comparisonId === null || (is_array($comparisonId) && count($comparisonId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $comparisonId when calling comparisonsComparisonIdDelete'
            );
        }


        $resourcePath = '/comparisons/{comparisonId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($comparisonId !== null) {
            $resourcePath = str_replace(
                '{' . 'comparisonId' . '}',
                ObjectSerializer::toPathValue($comparisonId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation comparisonsComparisonIdGet
     *
     * 比較情報を取得
     *
     * @param  int $comparisonId comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdGet'] to see the possible values for this operation
     *
     * @throws \App\OpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \App\OpenAPI\Model\VideoComparison
     */
    public function comparisonsComparisonIdGet($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdGet'][0])
    {
        list($response) = $this->comparisonsComparisonIdGetWithHttpInfo($comparisonId, $contentType);
        return $response;
    }

    /**
     * Operation comparisonsComparisonIdGetWithHttpInfo
     *
     * 比較情報を取得
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdGet'] to see the possible values for this operation
     *
     * @throws \App\OpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \App\OpenAPI\Model\VideoComparison, HTTP status code, HTTP response headers (array of strings)
     */
    public function comparisonsComparisonIdGetWithHttpInfo($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdGet'][0])
    {
        $request = $this->comparisonsComparisonIdGetRequest($comparisonId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\App\OpenAPI\Model\VideoComparison' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\App\OpenAPI\Model\VideoComparison' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\App\OpenAPI\Model\VideoComparison', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\App\OpenAPI\Model\VideoComparison';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\OpenAPI\Model\VideoComparison',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation comparisonsComparisonIdGetAsync
     *
     * 比較情報を取得
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function comparisonsComparisonIdGetAsync($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdGet'][0])
    {
        return $this->comparisonsComparisonIdGetAsyncWithHttpInfo($comparisonId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation comparisonsComparisonIdGetAsyncWithHttpInfo
     *
     * 比較情報を取得
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function comparisonsComparisonIdGetAsyncWithHttpInfo($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdGet'][0])
    {
        $returnType = '\App\OpenAPI\Model\VideoComparison';
        $request = $this->comparisonsComparisonIdGetRequest($comparisonId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'comparisonsComparisonIdGet'
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function comparisonsComparisonIdGetRequest($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdGet'][0])
    {

        // verify the required parameter 'comparisonId' is set
        if ($comparisonId === null || (is_array($comparisonId) && count($comparisonId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $comparisonId when calling comparisonsComparisonIdGet'
            );
        }


        $resourcePath = '/comparisons/{comparisonId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($comparisonId !== null) {
            $resourcePath = str_replace(
                '{' . 'comparisonId' . '}',
                ObjectSerializer::toPathValue($comparisonId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation comparisonsComparisonIdPublishPost
     *
     * 比較情報を公開状態にする
     *
     * @param  int $comparisonId comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdPublishPost'] to see the possible values for this operation
     *
     * @throws \App\OpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function comparisonsComparisonIdPublishPost($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdPublishPost'][0])
    {
        $this->comparisonsComparisonIdPublishPostWithHttpInfo($comparisonId, $contentType);
    }

    /**
     * Operation comparisonsComparisonIdPublishPostWithHttpInfo
     *
     * 比較情報を公開状態にする
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdPublishPost'] to see the possible values for this operation
     *
     * @throws \App\OpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function comparisonsComparisonIdPublishPostWithHttpInfo($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdPublishPost'][0])
    {
        $request = $this->comparisonsComparisonIdPublishPostRequest($comparisonId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation comparisonsComparisonIdPublishPostAsync
     *
     * 比較情報を公開状態にする
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdPublishPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function comparisonsComparisonIdPublishPostAsync($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdPublishPost'][0])
    {
        return $this->comparisonsComparisonIdPublishPostAsyncWithHttpInfo($comparisonId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation comparisonsComparisonIdPublishPostAsyncWithHttpInfo
     *
     * 比較情報を公開状態にする
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdPublishPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function comparisonsComparisonIdPublishPostAsyncWithHttpInfo($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdPublishPost'][0])
    {
        $returnType = '';
        $request = $this->comparisonsComparisonIdPublishPostRequest($comparisonId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'comparisonsComparisonIdPublishPost'
     *
     * @param  int $comparisonId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsComparisonIdPublishPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function comparisonsComparisonIdPublishPostRequest($comparisonId, string $contentType = self::contentTypes['comparisonsComparisonIdPublishPost'][0])
    {

        // verify the required parameter 'comparisonId' is set
        if ($comparisonId === null || (is_array($comparisonId) && count($comparisonId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $comparisonId when calling comparisonsComparisonIdPublishPost'
            );
        }


        $resourcePath = '/comparisons/{comparisonId}/publish';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($comparisonId !== null) {
            $resourcePath = str_replace(
                '{' . 'comparisonId' . '}',
                ObjectSerializer::toPathValue($comparisonId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation comparisonsPost
     *
     * 比較情報を登録
     *
     * @param  \App\OpenAPI\Model\VideoComparison $videoComparison videoComparison (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsPost'] to see the possible values for this operation
     *
     * @throws \App\OpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \App\OpenAPI\Model\ComparisonsPost200Response
     */
    public function comparisonsPost($videoComparison, string $contentType = self::contentTypes['comparisonsPost'][0])
    {
        list($response) = $this->comparisonsPostWithHttpInfo($videoComparison, $contentType);
        return $response;
    }

    /**
     * Operation comparisonsPostWithHttpInfo
     *
     * 比較情報を登録
     *
     * @param  \App\OpenAPI\Model\VideoComparison $videoComparison (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsPost'] to see the possible values for this operation
     *
     * @throws \App\OpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \App\OpenAPI\Model\ComparisonsPost200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function comparisonsPostWithHttpInfo($videoComparison, string $contentType = self::contentTypes['comparisonsPost'][0])
    {
        $request = $this->comparisonsPostRequest($videoComparison, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\App\OpenAPI\Model\ComparisonsPost200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\App\OpenAPI\Model\ComparisonsPost200Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\App\OpenAPI\Model\ComparisonsPost200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\App\OpenAPI\Model\ComparisonsPost200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\OpenAPI\Model\ComparisonsPost200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation comparisonsPostAsync
     *
     * 比較情報を登録
     *
     * @param  \App\OpenAPI\Model\VideoComparison $videoComparison (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function comparisonsPostAsync($videoComparison, string $contentType = self::contentTypes['comparisonsPost'][0])
    {
        return $this->comparisonsPostAsyncWithHttpInfo($videoComparison, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation comparisonsPostAsyncWithHttpInfo
     *
     * 比較情報を登録
     *
     * @param  \App\OpenAPI\Model\VideoComparison $videoComparison (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function comparisonsPostAsyncWithHttpInfo($videoComparison, string $contentType = self::contentTypes['comparisonsPost'][0])
    {
        $returnType = '\App\OpenAPI\Model\ComparisonsPost200Response';
        $request = $this->comparisonsPostRequest($videoComparison, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'comparisonsPost'
     *
     * @param  \App\OpenAPI\Model\VideoComparison $videoComparison (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['comparisonsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function comparisonsPostRequest($videoComparison, string $contentType = self::contentTypes['comparisonsPost'][0])
    {

        // verify the required parameter 'videoComparison' is set
        if ($videoComparison === null || (is_array($videoComparison) && count($videoComparison) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $videoComparison when calling comparisonsPost'
            );
        }


        $resourcePath = '/comparisons';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($videoComparison)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($videoComparison));
            } else {
                $httpBody = $videoComparison;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
