openapi: 3.0.0
info:
  title: OpenAPI Tutorial
  description: OpenAPI Tutorial by halhorn
  version: 0.0.0
servers:
  - url: http://localhost:80/api/v1
    description: 開発用
paths:
  /register:
    post:
      tags:
        - "authentication"
      summary: 新規登録
      description: 詳細内容
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                handleName:
                  type: string
                carType:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - handleName
                - carType
                - email
                - password
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /login:
    post:
      tags:
        - "authentication"
      summary: ログイン
      description: 詳細内容
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /logout:
    post:
      tags:
        - "authentication"
      summary: ログアウト
      description: 詳細内容
      responses:
        "200":
          description: OK
          content: {}
  /me:
    get:
      tags:
        - "authentication"
      summary: ログイン済のユーザー情報を取得
      description: 詳細内容
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /comparisons:
    post:
      tags:
        - "comparisons"
      summary: 比較情報を登録
      description: 詳細内容
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/videoComparison"
      responses:
        "200":
          description: OK
          content: {}
  /comparisons/{comparisonId}:
    get:
      tags:
        - "comparisons"
      summary: 比較情報を取得
      description: 詳細内容
      parameters:
        - in: path
          name: comparisonId
          required: true
          schema:
            type: number
      responses:
        "200":
          description: アンケートの回答状態
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/videoComparison"
    delete:
      tags:
        - "comparisons"
      summary: 比較情報を削除
      description: 詳細内容
      parameters:
        - in: path
          name: comparisonId
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content: {}
  /comparisons/{comparisonId}/publish:
    post:
      tags:
        - "comparisons"
      summary: 比較情報を公開状態にする
      description: 詳細内容
      parameters:
        - in: path
          name: comparisonId
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content: {}
  /oauth/youtube/url:
    get:
      tags:
        - "youtube"
      summary: 認可画面のURLを取得
      description: 詳細内容
      responses:
        "200":
          description: アンケートの回答状態
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirectUrl:
                    type: string
                    description: "認可画面のリダイレクト用URL"
                required:
                  - redirectUrl
  /oauth/youtube:
    post:
      tags:
        - "youtube"
      summary: アクセストークンを取得
      description: 詳細内容
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              required:
                - code
      responses:
        "200":
          description: 詳細内容
          content: {}
  /youtube/videos:
    post:
      tags:
        - "youtube"
      summary: 本人がアップロードした動画一覧を取得
      description: 詳細内容
      responses:
        "200":
          description: アンケートの回答状態
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    url:
                      type: string
                      description: "url"
                    title:
                      type: string
                      description: "タイトル"
                    description:
                      type: string
                      description: "説明"
                    thumbnailUrl:
                      type: string
                      description: "サムネ画像のURL"
                  required:
                    - url
                    - title
                    - description
                    - thumbnailUrl
  /operationLog:
    post:
      tags:
        - "operationLog"
      summary: 操作ログを送信
      description: 詳細内容
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestOperationLog"
      responses:
        "200":
          description: OK
          content: {}

components:
  schemas:
    User:
      description: ユーザー情報
      type: object
      properties:
        id:
          type: number
          description: "ユーザーID"
        hundleName:
          type: string
          description: "ハンドルネーム"
      required:
        - id
        - hundleName

    Video:
      description: 動画情報
      type: object
      properties:
        url:
          type: string
        timeSt:
          type: string
        videoType:
          $ref: "#/components/schemas/videoType"
      required:
        - url
        - timeSt
        - videoType

    videoComparison:
      description: 動画比較情報
      type: object
      properties:
        userId:
          type: number
        memo:
          type: string
        title:
          type: string
        video1:
          $ref: "#/components/schemas/Video"
        video2:
          $ref: "#/components/schemas/Video"
      required:
        - video1
        - video2
    requestOperationLog:
      description: リクエスト 操作ログ
      type: object
      properties:
        operationCd:
          $ref: "#/components/schemas/operationCd"
      required:
        - operationCd
    videoType:
      description: 動画タイプ
      enum: [1, 2]
      x-enum-varnames: [YOUTUBE, LOCAL]
    operationCd:
      description: |
        ■操作コード  
        ENABLE_SENSOR: センサーを有効にする  
        CALIBRATION: キャリブレーション  
        CALIBRATION_BEFORE_SETTING: 直前設定を使う  
        CALIBRATION_NEXT_1: キャリブレーション1 次へ  
        CALIBRATION_NEXT_2: キャリブレーション2 次へ  
        MAX_14_G: Max1.4G  
        MAX_10_G: Max1.0G  
        VOICE_OUTPUT_ON: 音声出力ON  
        VOICE_OUTPUT_OFF: 音声出力OFF  
        GBOWL: GBowl  
        GINDICATOR: GIndicator
      enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
      x-enum-varnames:
        [
          ENABLE_SENSOR,
          CALIBRATION,
          CALIBRATION_BEFORE_SETTING,
          CALIBRATION_NEXT_1,
          CALIBRATION_NEXT_2,
          MAX_14_G,
          MAX_10_G,
          VOICE_OUTPUT_ON,
          VOICE_OUTPUT_OFF,
          GBOWL,
          GINDICATOR,
        ]
