/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * ログイン状態
     * @type {boolean}
     * @memberof InlineResponse2004
     */
    isLogined: boolean;
    /**
     * Youtube認可状態
     * @type {boolean}
     * @memberof InlineResponse2004
     */
    isYoutubeAuthroized: boolean;
    /**
     * 
     * @type {User}
     * @memberof InlineResponse2004
     */
    user: User;
}

export function InlineResponse2004FromJSON(json: any): InlineResponse2004 {
    return InlineResponse2004FromJSONTyped(json, false);
}

export function InlineResponse2004FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2004 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isLogined': json['isLogined'],
        'isYoutubeAuthroized': json['isYoutubeAuthroized'],
        'user': UserFromJSON(json['user']),
    };
}

export function InlineResponse2004ToJSON(value?: InlineResponse2004 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isLogined': value.isLogined,
        'isYoutubeAuthroized': value.isYoutubeAuthroized,
        'user': UserToJSON(value.user),
    };
}

