<?php
/**
 * OperationCd
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  App\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Tutorial
 *
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\OpenAPI\Model;
use \App\OpenAPI\ObjectSerializer;

/**
 * OperationCd Class Doc Comment
 *
 * @category Class
 * @description ■操作コード   ENABLE_SENSOR: センサーを有効にする   CALIBRATION: キャリブレーション   CALIBRATION_BEFORE_SETTING: 直前設定を使う   CALIBRATION_NEXT_1: キャリブレーション1 次へ   CALIBRATION_NEXT_2: キャリブレーション2 次へ   MAX_14_G: Max1.4G   MAX_10_G: Max1.0G   VOICE_OUTPUT_ON: 音声出力ON   VOICE_OUTPUT_OFF: 音声出力OFF   GBOWL: GBowl   GINDICATOR: GIndicator
 * @package  App\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OperationCd
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_ENABLE_SENSOR = 1;

    public const NUMBER_CALIBRATION = 2;

    public const NUMBER_CALIBRATION_BEFORE_SETTING = 3;

    public const NUMBER_CALIBRATION_NEXT_1 = 4;

    public const NUMBER_CALIBRATION_NEXT_2 = 5;

    public const NUMBER_MAX_14_G = 6;

    public const NUMBER_MAX_10_G = 7;

    public const NUMBER_VOICE_OUTPUT_ON = 8;

    public const NUMBER_VOICE_OUTPUT_OFF = 9;

    public const NUMBER_GBOWL = 10;

    public const NUMBER_GINDICATOR = 11;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_ENABLE_SENSOR,
            self::NUMBER_CALIBRATION,
            self::NUMBER_CALIBRATION_BEFORE_SETTING,
            self::NUMBER_CALIBRATION_NEXT_1,
            self::NUMBER_CALIBRATION_NEXT_2,
            self::NUMBER_MAX_14_G,
            self::NUMBER_MAX_10_G,
            self::NUMBER_VOICE_OUTPUT_ON,
            self::NUMBER_VOICE_OUTPUT_OFF,
            self::NUMBER_GBOWL,
            self::NUMBER_GINDICATOR
        ];
    }
}


