<?php
/**
 * OperationCd
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  App\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Tutorial
 *
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\OpenAPI\Model;
use \App\OpenAPI\ObjectSerializer;

/**
 * OperationCd Class Doc Comment
 *
 * @category Class
 * @package  App\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OperationCd
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_OPEN_MODAL_CLICK = 1;

    public const NUMBER_OPEN_CLICK = 2;

    public const NUMBER_SAVE_MODAL_CLICK = 3;

    public const NUMBER_SAVE_CLICK = 4;

    public const NUMBER_SYNC_RUN_CLICK = 5;

    public const NUMBER_SYNC_STOP_CLICK = 6;

    public const NUMBER_SYNC_SHARE_CLICK = 7;

    public const NUMBER_PLAYER_ONE_URL_ENTER = 8;

    public const NUMBER_PLAYER_ONE_YOUTUBE_SEARCH_CLICK = 9;

    public const NUMBER_PLAYER_ONE_LOCAL_SELECT = 10;

    public const NUMBER_PLAYER_TWO_URL_ENTER = 11;

    public const NUMBER_PLAYER_TWO_YOUTUBE_SEARCH_CLICK = 12;

    public const NUMBER_PLAYER_TWO_LOCAL_SELECT = 13;

    public const NUMBER_YOUTUBE_OAUTH_CLICK = 14;

    public const NUMBER_YOUTUBE_SELECT = 15;

    public const NUMBER_NAV_HOME_CLICK = 16;

    public const NUMBER_NAV_LOGIN_CLICK = 17;

    public const NUMBER_NAV_LOGOUT_CLICK = 18;

    public const NUMBER_NAV_REGISTER_CLICK = 19;

    public const NUMBER_NAV_ABOUT_APP_CLICK = 20;

    public const NUMBER_NAV_INQUIRY = 21;

    public const NUMBER_HOME_OPEN_CLICK = 22;

    public const NUMBER_HOME_DELETE_CLICK = 23;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_OPEN_MODAL_CLICK,
            self::NUMBER_OPEN_CLICK,
            self::NUMBER_SAVE_MODAL_CLICK,
            self::NUMBER_SAVE_CLICK,
            self::NUMBER_SYNC_RUN_CLICK,
            self::NUMBER_SYNC_STOP_CLICK,
            self::NUMBER_SYNC_SHARE_CLICK,
            self::NUMBER_PLAYER_ONE_URL_ENTER,
            self::NUMBER_PLAYER_ONE_YOUTUBE_SEARCH_CLICK,
            self::NUMBER_PLAYER_ONE_LOCAL_SELECT,
            self::NUMBER_PLAYER_TWO_URL_ENTER,
            self::NUMBER_PLAYER_TWO_YOUTUBE_SEARCH_CLICK,
            self::NUMBER_PLAYER_TWO_LOCAL_SELECT,
            self::NUMBER_YOUTUBE_OAUTH_CLICK,
            self::NUMBER_YOUTUBE_SELECT,
            self::NUMBER_NAV_HOME_CLICK,
            self::NUMBER_NAV_LOGIN_CLICK,
            self::NUMBER_NAV_LOGOUT_CLICK,
            self::NUMBER_NAV_REGISTER_CLICK,
            self::NUMBER_NAV_ABOUT_APP_CLICK,
            self::NUMBER_NAV_INQUIRY,
            self::NUMBER_HOME_OPEN_CLICK,
            self::NUMBER_HOME_DELETE_CLICK
        ];
    }
}


