/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 動画タイプ
 * @export
 * @enum {string}
 */
export enum VideoType {
    YOUTUBE = 1,
    LOCAL = 2
}

export function VideoTypeFromJSON(json: any): VideoType {
    return VideoTypeFromJSONTyped(json, false);
}

export function VideoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoType {
    return json as VideoType;
}

export function VideoTypeToJSON(value?: VideoType | null): any {
    return value as any;
}

