/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {
    /**
     * url
     * @type {string}
     * @memberof InlineResponse2003
     */
    url: string;
    /**
     * タイトル
     * @type {string}
     * @memberof InlineResponse2003
     */
    title: string;
    /**
     * 説明
     * @type {string}
     * @memberof InlineResponse2003
     */
    description: string;
    /**
     * サムネ画像のURL
     * @type {string}
     * @memberof InlineResponse2003
     */
    thumbnailUrl: string;
}

export function InlineResponse2003FromJSON(json: any): InlineResponse2003 {
    return InlineResponse2003FromJSONTyped(json, false);
}

export function InlineResponse2003FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'title': json['title'],
        'description': json['description'],
        'thumbnailUrl': json['thumbnailUrl'],
    };
}

export function InlineResponse2003ToJSON(value?: InlineResponse2003 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'title': value.title,
        'description': value.description,
        'thumbnailUrl': value.thumbnailUrl,
    };
}

